#                                                       ML PROJECT

### 1 - INTRODUCTION

Description...............................

### 2 - IMPORTS

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### 3 - LOADING DATASETS

In [28]:
# Loading them into dataframes for easy manipulations

fs1 = pd.read_csv("data/FS1.txt", sep="\t", header=None)
ps2 = pd.read_csv("data/PS2.txt", sep="\t", header=None)
profile = pd.read_csv("data/profile.txt", sep="\t", header=None)

# extraction 
valve_condition = profile.iloc[:,1]

In [21]:
print(fs1.shape)
fs1.head(5)

(2205, 600)

,0,1,2,3,4,5,6,7,8,9,...,590,591,592,593,594,595,596,597,598,599
0,8.990,0.770,0.641,0.006,0.000,0.000,0.001,0.003,0.001,0.001,...,7.743,7.992,7.919,7.773,7.955,7.823,7.963,7.876,7.738,8.036
1,8.919,0.815,0.709,0.009,0.004,0.000,0.001,0.000,0.000,0.001,...,7.831,8.003,7.923,7.745,7.867,7.747,7.969,7.969,7.963,7.890
2,9.179,0.683,0.528,0.008,0.003,0.001,0.003,0.003,0.004,0.006,...,7.862,7.815,7.894,7.743,7.936,7.770,7.982,7.873,7.898,7.952
3,9.034,0.728,0.595,0.009,0.001,0.004,0.003,0.003,0.003,0.001,...,7.631,7.949,7.773,8.054,7.827,8.011,7.919,7.938,7.877,7.773
4,8.729,0.705,0.446,0.014,0.007,0.003,0.001,0.003,0.001,0.000,...,7.771,7.936,7.919,7.946,7.804,7.983,7.838,7.882,7.894,7.825

In [22]:
print(ps2.shape)
ps2.head(5)

(2205, 6000)

,0,1,2,3,4,5,6,7,8,9,...,5990,5991,5992,5993,5994,5995,5996,5997,5998,5999
0,125.50,125.39,125.40,125.03,124.05,123.18,104.01,56.500,23.992,18.406,...,125.02,125.00,125.10,125.09,124.98,124.91,124.98,125.11,125.14,125.10
1,125.06,125.08,125.09,124.69,123.84,123.14,103.63,63.687,28.359,21.711,...,124.80,124.88,125.13,125.22,125.09,124.98,125.06,125.13,125.09,125.04
2,125.13,125.27,125.23,124.74,123.94,123.23,106.35,60.516,26.258,19.258,...,124.61,124.69,124.74,124.71,124.59,124.64,124.74,124.73,124.77,124.88
3,124.93,124.96,124.92,124.41,123.60,122.88,103.99,58.859,27.781,21.469,...,124.82,124.79,124.69,124.69,124.77,124.83,124.69,124.53,124.51,124.59
4,124.72,124.74,124.66,124.31,123.57,122.74,105.94,62.648,30.875,23.883,...,124.80,124.67,124.49,124.56,124.69,124.62,124.45,124.41,124.47,124.51

In [23]:
print(valve_condition.shape)
valve_condition.head(5)

(2204,)

0    100
1    100
2    100
3    100
4    100
Name: 100, dtype: int64

### 4 - UNDERSTANDING THE DATA

Nous constatons que il y'a pas de donnees manquants dans notre dataset. En lisant la documentation de notre projet, on constate : 
- PS2.txt contient les donnees du cateur de Pression "PS2" en bar avec une frequence de 100 Hz dans la valve
- FS1.txt contient les donnees du capteur de debit volumique "FS1" en l/min avec une frequence de 10Hz dans la valve
- valve_condition contient les donnees des coditions de fonctionnement de la valve

### 5 - DESCRIPTIVE STATISTIQUES

In [24]:
fs1.describe()

,0,1,2,3,4,5,6,7,8,9,...,590,591,592,593,594,595,596,597,598,599
count,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,...,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000
mean,8.287100,0.857298,0.563584,0.031154,0.003567,0.002926,0.002683,0.002458,0.002436,0.002311,...,7.638567,7.638928,7.642123,7.641907,7.638804,7.643067,7.637415,7.645035,7.638999,7.637983
std,0.480969,0.125100,0.152903,0.039403,0.002810,0.002540,0.002501,0.002410,0.002451,0.002378,...,0.530204,0.529731,0.530209,0.530325,0.529648,0.530317,0.529648,0.530884,0.530817,0.529553
min,7.033000,0.522000,0.309000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.106000,1.117000,1.119000,1.123000,1.109000,1.111000,1.118000,1.120000,1.124000,1.120000
25%,7.961000,0.773000,0.445000,0.009000,0.001000,0.001000,0.000000,0.000000,0.000000,0.000000,...,7.514000,7.515000,7.518000,7.515000,7.519000,7.518000,7.513000,7.525000,7.510000,7.519000
50%,8.278000,0.855000,0.531000,0.016000,0.003000,0.003000,0.003000,0.001000,0.001000,0.001000,...,7.712000,7.709000,7.711000,7.714000,7.706000,7.714000,7.707000,7.713000,7.710000,7.708000
75%,8.610000,0.944000,0.656000,0.036000,0.005000,0.004000,0.004000,0.004000,0.004000,0.004000,...,7.815000,7.815000,7.818000,7.823000,7.813000,7.820000,7.813000,7.821000,7.826000,7.815000
max,11.754000,1.488000,0.985000,0.298000,0.015000,0.013000,0.011000,0.011000,0.012000,0.012000,...,8.060000,8.078000,8.072000,8.064000,8.073000,8.080000,8.076000,8.083000,8.078000,8.087000

In [25]:
ps2.describe()

,0,1,2,3,4,5,6,7,8,9,...,5990,5991,5992,5993,5994,5995,5996,5997,5998,5999
count,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,...,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000,2205.000000
mean,123.362422,123.364358,123.339202,122.831868,121.808503,120.693455,104.294819,64.491438,35.220531,27.355589,...,123.359583,123.356580,123.355896,123.360023,123.361705,123.358848,123.358966,123.364444,123.364957,123.361741
std,3.701729,3.694412,3.700527,3.819922,3.746546,3.541433,9.616892,8.636717,3.792106,3.286553,...,3.701453,3.705096,3.702194,3.701239,3.698299,3.694301,3.700553,3.703952,3.700664,3.703531
min,119.610000,119.630000,118.920000,118.650000,115.830000,97.289000,27.031000,0.977000,1.133000,1.203000,...,119.140000,119.630000,119.680000,119.590000,119.690000,119.520000,119.650000,119.650000,119.600000,119.520000
25%,121.630000,121.670000,121.660000,120.560000,118.830000,117.690000,96.664000,58.883000,33.398000,25.523000,...,121.630000,121.650000,121.670000,121.660000,121.660000,121.670000,121.670000,121.650000,121.630000,121.630000
50%,123.040000,123.040000,123.010000,122.620000,122.060000,121.520000,105.080000,64.773000,35.180000,27.398000,...,123.040000,123.040000,123.060000,123.030000,123.030000,123.030000,123.020000,123.020000,123.020000,123.040000
75%,125.100000,125.100000,125.090000,124.830000,124.480000,124.270000,113.020000,71.297000,37.289000,29.266000,...,125.100000,125.120000,125.110000,125.120000,125.110000,125.090000,125.100000,125.110000,125.130000,125.110000
max,165.480000,165.260000,165.530000,165.690000,160.570000,125.220000,117.390000,79.102000,44.617000,35.398000,...,165.570000,165.730000,165.560000,165.350000,165.440000,165.430000,165.440000,165.630000,165.360000,165.340000

In [26]:
valve_condition.describe()

count    2204.000000
mean       90.689655
std        10.682385
min        73.000000
25%        80.000000
50%       100.000000
75%       100.000000
max       100.000000
Name: 100, dtype: float64

### 6 - MISSING VALUES

In [27]:
print("Missing values summary:\n")
print(f"Valve Condition : {valve_condition.isna().sum()}")
print(f"PS2             : {ps2.isna().sum().sum()}")
print(f"FS1             : {fs1.isna().sum().sum()}")

Missing values summary:

Valve Condition : 0
PS2             : 0
FS1             : 0

### 7 - STRUCTURATION DES DONNEES

Grace a la documentation, nous comprenons que les donnees sont formatees d'une facon non conventionnnelle. Le donnees sont enregistré par cycle et enregiste sur une meme ligne avec une frequence d'echantillonage. Donc une ligne representre les donnees enregistre pour un cycle complet. 
Pour un cycle complet, on a : 
- Pression (PS2) avec pour frequence 100 Hz: 60 seconds * 100 mesures/seconds = 6000 mesures.
- Debit volumique (FS1) avec pour frequence 10 Hz: 60 seconds * 10 mesures/seconds = 600 mesures
Ca correspond exactement aux nombre de colonnes de nos dataset respectives

Donc nous devons proceder aux traitement des donnees pour rendre les donnees exploitable.

In [ ]:
# Comme notre tache concerne une classification binaire,

0    1    2  3    4
3    100  0  130  1    211
20   100  0  90   1    211
100  100  0  90   1    211
                  0     19
20   100  0  130  1     11
                      ...
100  100  1  100  1      1
          2  100  1      1
             90   1      1
             115  1      1
             130  1      1
Name: count, Length: 180, dtype: int64